version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vibe
    main: ./main.go
    binary: vibe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: vibe
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}"
    files:
      - vibe.plugin.zsh
      - _vibe
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

homebrew_casks:
  - repository:
      owner: skymoore
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/skymoore/vibe-zsh
    description: "Transform natural language into shell commands using AI"
    license: GPL-3.0
    dependencies:
      - formula: zsh
    caveats: |-
      vibe requires Oh My Zsh for Ctrl+G functionality.

      vibe has been installed to: #{staged_path}

      If Oh My Zsh is installed, vibe has been automatically configured in ~/.zshrc.
      Please run: source ~/.zshrc

      If Oh My Zsh is not installed, install it: sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\"

      Then add the following to your ~/.zshrc:
        plugins=(... vibe)
        export PATH=\"#{staged_path}/bin:$PATH\"
        source \"#{staged_path}/vibe.plugin.zsh\"
        fpath=(#{staged_path} $fpath)

      And run: source ~/.zshrc

      Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):
        export VIBE_API_URL=\"http://localhost:11434/v1\"
        export VIBE_MODEL=\"llama3:8b\"

      Use Ctrl+G to transform natural language into commands!

    hooks:
      post:
        install: |-
          oh_my_zsh_dir = "#{Dir.home}/.oh-my-zsh"
          zshrc_path = "#{Dir.home}/.zshrc"
          install_path = staged_path

          unless Dir.exist?(oh_my_zsh_dir)
            puts "Warning: Oh My Zsh is not installed. vibe requires Oh My Zsh for Ctrl+G functionality."
            puts "Please install Oh My Zsh: sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
            puts "After installation, add the following to your ~/.zshrc:"
            puts "  plugins=(... vibe)"
            puts "  export PATH=\"#{install_path}/bin:$PATH\""
            puts "  source \"#{install_path}/vibe.plugin.zsh\""
            puts "  fpath=(#{install_path} $fpath)"
            puts "Then source ~/.zshrc"
          else
            zshrc_content = File.read(zshrc_path) rescue ""
            
            unless zshrc_content =~ /\bvibe\b/
              puts "Adding 'vibe' to plugins in ~/.zshrc"
              if zshrc_content.match?(/plugins=\(([\s\S]*?)\)/m)
                zshrc_content.gsub!(/plugins=\(([\s\S]*?)\)/m) do |m|
                  plugins_list = $1.strip
                  if plugins_list.empty?
                    "plugins=(vibe)"
                  else
                    if plugins_list.include?("\n")
                      "plugins=(#{plugins_list}\n  vibe\n)"
                    else
                      "plugins=(#{plugins_list} vibe)"
                    end
                  end
                end
              else
                zshrc_content += "\nplugins=(vibe)\n"
              end
            end

            path_line = "export PATH=\"#{install_path}/bin:$PATH\""
            source_line = "source \"#{install_path}/vibe.plugin.zsh\""
            fpath_line = "fpath+=(#{install_path})"

            unless zshrc_content.include?(path_line) || zshrc_content =~ /export PATH=.*vibe-zsh.*bin/
              zshrc_content += "\n#{path_line}\n"
            end

            unless zshrc_content.include?(source_line) || zshrc_content =~ /source.*vibe\.plugin\.zsh/
              zshrc_content += "#{source_line}\n"
            end

            unless zshrc_content.include?(fpath_line) || zshrc_content =~ /fpath.*vibe-zsh/
              zshrc_content += "#{fpath_line}\n"
            end

            File.write(zshrc_path, zshrc_content)

            puts "vibe setup complete. Please run: source ~/.zshrc"
          end

notarize:
  macos:
    - enabled: true
      ids:
        - vibe
      sign:
        certificate: "{{ .Env.APPLE_CERT_B64 }}"
        password: "{{ .Env.APPLE_CERT_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.APPLE_NOTARY_KEY_ISSUER_ID }}"
        key_id: "{{ .Env.APPLE_NOTARY_KEY_ID }}"
        key: "{{ .Env.APPLE_NOTARY_KEY_B64 }}"

release:
  github:
    owner: skymoore
    name: vibe-zsh
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### Homebrew (Recommended)
    ```bash
    brew tap skymoore/tap
    brew install --cask vibe-zsh
    ```

    ### One-line install script
    ```bash
    curl -fsSL https://raw.githubusercontent.com/skymoore/vibe-zsh/main/install.sh | bash
    ```

    See the [README](https://github.com/skymoore/vibe-zsh#installation) for more installation options.
