version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vibe
    main: ./main.go
    binary: vibe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: vibe
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - vibe.plugin.zsh
      - _vibe
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

homebrew_casks:
  - repository:
      owner: skymoore
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/skymoore/vibe-zsh
    description: "Transform natural language into shell commands using AI"
    license: GPL-3.0
    caveats: |
      vibe has been installed to:
        #{staged_path}

      To activate vibe, add the following to your ~/.zshrc:

        export PATH=\"#{staged_path}:$PATH\"
        source \"#{staged_path}/vibe.plugin.zsh\"
        fpath=(#{staged_path} $fpath)

      Then reload your shell:
        source ~/.zshrc

      Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):
        export VIBE_API_URL=\"http://localhost:11434/v1\"
        export VIBE_MODEL=\"llama3:8b\"

      Use Ctrl+G to transform natural language into commands!

release:
  github:
    owner: skymoore
    name: vibe-zsh
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### Homebrew (Recommended)
    ```bash
    brew tap skymoore/tap
    brew install vibe
    ```

    ### One-line install script
    ```bash
    curl -fsSL https://raw.githubusercontent.com/skymoore/vibe-zsh/main/install.sh | bash
    ```

    See the [README](https://github.com/skymoore/vibe-zsh#installation) for more installation options.
