version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vibe
    main: ./main.go
    binary: vibe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: vibe
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}"
    files:
      - vibe.plugin.zsh
      - _vibe
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

homebrew:
  - tap:
      owner: skymoore
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    folder: Formula
    homepage: https://github.com/skymoore/vibe-zsh
    description: "Transform natural language into shell commands using AI"
    license: GPL-3.0
    dependencies:
      - name: zsh
    install: |
      bin.install "vibe"
      prefix.install "vibe.plugin.zsh", "_vibe"
    post_install: |
      ohai "To activate vibe, add to ~/.zshrc:"
      puts 'export PATH="#{opt_bin}:$PATH"'
      puts 'source "#{opt_prefix}/vibe.plugin.zsh"'
      puts 'fpath=(#{opt_prefix} $fpath)'
      puts "Reload: source ~/.zshrc"
      puts "Configure: export VIBE_API_URL=... (see README)"
    caveats: "Use Ctrl+G to transform commands! See README for details."
    bottle: true

signs:
  - artifacts: all
    args: ["--keychain", "temp.keychain", "--timestamp"]

notarize:
  - bundle_id: dev.vibe-zsh
    apple_id: "{{ .Env.APPLE_ID }}"

release:
  github:
    owner: skymoore
    name: vibe-zsh
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### Homebrew (Recommended)
    ```bash
    brew tap skymoore/tap
    brew install vibe
    ```

    ### One-line install script
    ```bash
    curl -fsSL https://raw.githubusercontent.com/skymoore/vibe-zsh/main/install.sh | bash
    ```

    See the [README](https://github.com/skymoore/vibe-zsh#installation) for more installation options.
