version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: vibe
    main: ./main.go
    binary: vibe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: vibe
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}"
    files:
      - vibe.plugin.zsh
      - _vibe
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

homebrew_casks:
  - repository:
      owner: skymoore
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/skymoore/vibe-zsh
    description: "Transform natural language into shell commands using AI"
    license: GPL-3.0
    dependencies:
      - formula: zsh
    caveats: |-
      vibe requires Oh My Zsh for Ctrl+G functionality.

      If Oh My Zsh is installed, vibe has been automatically configured.
      Please run: source ~/.zshrc

      If Oh My Zsh is not installed, install it first:
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

      Then add 'vibe' to your plugins in ~/.zshrc:
        plugins=(... vibe)

      Configure your AI provider (see https://github.com/skymoore/vibe-zsh#configuration):
        export VIBE_API_URL="http://localhost:11434/v1"
        export VIBE_MODEL="llama3:8b"

      Use Ctrl+G to transform natural language into commands!

    hooks:
      post:
        install: |-
          require 'fileutils'
          
          oh_my_zsh_dir = "#{Dir.home}/.oh-my-zsh"
          custom_plugins_dir = "#{oh_my_zsh_dir}/custom/plugins"
          vibe_plugin_dir = "#{custom_plugins_dir}/vibe"
          zshrc_path = "#{Dir.home}/.zshrc"
          
          binary_link = "/opt/homebrew/bin/vibe-zsh"
          if File.exist?(binary_link) && File.symlink?(binary_link)
            install_path = File.readlink(binary_link)
          else
            install_path = staged_path
          end

          unless Dir.exist?(oh_my_zsh_dir)
            puts "Warning: Oh My Zsh is not installed. vibe requires Oh My Zsh for Ctrl+G functionality."
            puts "Please install Oh My Zsh: sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
            puts "After installation, add 'vibe' to your plugins in ~/.zshrc and run: source ~/.zshrc"
            exit 0
          end

          FileUtils.mkdir_p(custom_plugins_dir) unless Dir.exist?(custom_plugins_dir)
          
          if Dir.exist?(vibe_plugin_dir)
            FileUtils.rm_rf(vibe_plugin_dir)
          end
          FileUtils.mkdir_p(vibe_plugin_dir)

          ["vibe", "vibe.plugin.zsh", "_vibe", "LICENSE", "README.md"].each do |file|
            src = File.join(install_path, file)
            dst = File.join(vibe_plugin_dir, file)
            if File.exist?(src)
              FileUtils.cp(src, dst)
              FileUtils.chmod(0755, dst) if file == "vibe"
            end
          end

          zshrc_content = File.read(zshrc_path) rescue ""
          modified = false
          
          unless zshrc_content =~ /\bvibe\b/ && zshrc_content =~ /plugins=/
            if zshrc_content.match?(/plugins=\(([\s\S]*?)\)/m)
              zshrc_content.gsub!(/plugins=\(([\s\S]*?)\)/m) do |m|
                plugins_list = $1.strip
                if plugins_list =~ /\bvibe\b/
                  m
                elsif plugins_list.empty?
                  "plugins=(vibe)"
                elsif plugins_list.include?("\n")
                  "plugins=(#{plugins_list}\n  vibe\n)"
                else
                  "plugins=(#{plugins_list} vibe)"
                end
              end
              modified = true
            else
              zshrc_content += "\nplugins=(vibe)\n"
              modified = true
            end
          end

          if modified
            File.write(zshrc_path, zshrc_content)
            puts "✓ Added vibe to plugins in ~/.zshrc"
          end
          
          puts "✓ vibe plugin installed to #{vibe_plugin_dir}"
          puts "✓ vibe setup complete. Please run: source ~/.zshrc"

notarize:
  macos:
    - enabled: true
      ids:
        - vibe
      sign:
        certificate: "{{ .Env.APPLE_CERT_B64 }}"
        password: "{{ .Env.APPLE_CERT_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.APPLE_NOTARY_KEY_ISSUER_ID }}"
        key_id: "{{ .Env.APPLE_NOTARY_KEY_ID }}"
        key: "{{ .Env.APPLE_NOTARY_KEY_B64 }}"

release:
  github:
    owner: skymoore
    name: vibe-zsh
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Installation

    ### Homebrew (Recommended)
    ```bash
    brew tap skymoore/tap
    brew install --cask vibe-zsh
    ```

    ### One-line install script
    ```bash
    curl -fsSL https://raw.githubusercontent.com/skymoore/vibe-zsh/main/install.sh | bash
    ```

    See the [README](https://github.com/skymoore/vibe-zsh#installation) for more installation options.
