name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
      APPLE_CERT_B64: ${{ secrets.APPLE_CERT_B64 }}
      APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_NOTARY_KEY_B64: ${{ secrets.APPLE_NOTARY_KEY_B64 }}
      APPLE_NOTARY_KEY_ID: ${{ secrets.APPLE_NOTARY_KEY_ID }}
      APPLE_NOTARY_KEY_ISSUER_ID: ${{ secrets.APPLE_NOTARY_KEY_ISSUER_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'

      - name: Install GoReleaser
        run: brew install goreleaser

      - name: Decode and Import Certificate
        run: |
          echo "$APPLE_CERT_B64" | base64 -d > cert.p12
          security create-keychain -p temp temp.keychain
          security default-keychain -s temp.keychain
          security unlock-keychain -p temp temp.keychain
          security import cert.p12 -k temp.keychain -P "$APPLE_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k temp temp.keychain
          rm cert.p12

      - name: Run GoReleaser
        run: goreleaser release --clean --skip=validate --id vibe

      - name: Cleanup Keychain
        if: always()
        run: security delete-keychain temp.keychain
